name: mlba

concurrency:
  group: mlba-${{ github.ref }}
  cancel-in-progress: true
  
on: [push, workflow_dispatch]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip3 install --upgrade ruff

      - name: Run ruff
        run: ruff check ./src
  
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: "3.11"
          

      - name: Install dependencies
        run: |
          pip3 install -U pip
          # pip3 install -r requirements.txt
          pip3 install numpy mypy
      
      - name: versions
        run: pip3 freeze
      
      - name: Run mypy
        run: mypy --install-types --cache-dir ./.mypy-cache ./src
    
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
    name: Python ${{ matrix.python-version }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: python --version
      - run: pip install --upgrade pip numpy pandas matplotlib scikit-learn pytest
      - run: pytest -rP -p no:cacheprovider

