name: deep-learning-similarity

concurrency:
  group: deep-learning-similarity-${{ github.ref }}
  cancel-in-progress: true
  
on: [push, workflow_dispatch]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip3 install --upgrade ruff

      - name: Run ruff
        run: ruff check ./src
  
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: "3.11"
          

      - name: Install dependencies
        run: |
          pip3 install -U pip
          # pip3 install -r requirements.txt
          pip3 install mypy
      
      - name: versions
        run: pip3 freeze
      
      - name: Run mypy
        run: mypy --install-types ./src
    
